version: '3.8'

services:
  web:
    build: .
    command: sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5001"
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=testing
      - FLASK_RUN_PORT=5001

  test:
    build: .
    command: sh -c "flask db upgrade && pytest"
    depends_on:
      - web
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=testing
      - FLASK_RUN_PORT=5001
    volumes:
      - .:/app
