version: '3.8'

services:
  web:
    build: .
    command: sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
