"""Alembic Environment Configuration Script.

This script configures how Alembic runs migrations against the database. It has been
heavily customized away from the default, generic `flask db init` boilerplate to support
a Clean Architecture design pattern and production-safe continuous deployment workflows.

Key Architectural Differences From Default Setup:
--------------------------------------------------
1. Unified Metadata Registry Integration:
   - Default: Standard setups require manually importing and merging individual table or
     declarative base metadata targets into `target_metadata`.
   - Your Setup: Hooks directly into the single centralized `metadata` registry from
     `app.models.base`. This guarantees that any decoupled table schemas are automatically
     discovered during `flask db migrate` runs without explicit maintenance.

2. Application Context & Imperative ORM Bootstrapping:
   - Default: Alembic is typically completely detached from Flask's application configurations
     when executed via raw CLI, leading to hardcoded connection string overrides.
   - Your Setup: Safely instantiates transient application contexts or extracts active settings
     via `current_app` to dynamically bind `SQLALCHEMY_DATABASE_URI`. Crucially, it triggers
     `start_mappers(current_app)` in online migration blocks to ensure relationships and validation
     rules map cleanly during migrations.

3. Intelligent Empty Migration Suppression:
   - Default: Running an autogenerated migration check when no modifications have occurred results
     in a redundant, blank migration file being generated.
   - Your Setup: Implements `process_revision_directives` to intercept compilation logic. If no
     structural changes are captured between models and database status, migration file generation
     is cleanly aborted with a skipped log notification.
"""

import logging
import os
from logging.config import fileConfig

from alembic import context as alembic_context
from flask import current_app

from app import create_app
from app.config import DevelopmentConfig, ProductionConfig, TestingConfig
from app.models.base import metadata  # Centralized unified metadata registry
from app.orm import start_mappers

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = alembic_context.config

# Interpret the config file for Python logging.
fileConfig(config.config_file_name)
logger = logging.getLogger('alembic.env')

# Define a dictionary to map FLASK_ENV strings to your config classes
CONFIG_MAPPING = {
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'testing': TestingConfig,
    'default': DevelopmentConfig,  # Fallback if FLASK_ENV is not set or recognized
}


def get_alembic_url():
    """Dynamically loads Flask app config to get SQLAlchemy URL for Alembic."""
    try:
        if current_app:
            return current_app.config.get('SQLALCHEMY_DATABASE_URI')
    except RuntimeError:
        pass

    flask_env = config.get_main_option('FLASK_ENV') or os.environ.get('FLASK_ENV', 'default')

    ConfigClass = CONFIG_MAPPING.get(flask_env)
    if not ConfigClass:
        raise ValueError(f"Unknown FLASK_ENV '{flask_env}'. Add it to CONFIG_MAPPING in env.py or set FLASK_ENV.")

    temp_app = create_app(ConfigClass)
    with temp_app.app_context():
        return temp_app.config.get('SQLALCHEMY_DATABASE_URI')


def process_revision_directives(_context, _revision, directives):
    if getattr(config.cmd_opts, 'autogenerate', False):
        script = directives[0]
        if script.upgrade_ops.is_empty():
            directives[:] = []
            logger.info('No changes in schema detected, migration skipped.')


def get_engine():
    try:
        return current_app.extensions['migrate'].db.get_engine()
    except (TypeError, AttributeError):
        return current_app.extensions['migrate'].db.engine


def get_engine_url():
    try:
        return get_engine().url.render_as_string(hide_password=False).replace(
            '%', '%%')
    except AttributeError:
        return str(get_engine().url).replace('%', '%%')


# Point Alembic directly to our unified, centralized metadata object
target_metadata = metadata

print("Tables in target_metadata (from env.py):", target_metadata.tables.keys())
logger.info("Tables in target_metadata (from env.py): %s", target_metadata.tables.keys())

# Set the SQLAlchemy URL for Alembic using the safe function
alembic_config_url = get_alembic_url()
if not alembic_config_url:
    raise ValueError("SQLALCHEMY_DATABASE_URI not found in Flask app configuration.")
config.set_main_option('sqlalchemy.url', alembic_config_url)

# Initialize conf_args, using current_app.extensions['migrate'] as it should be
conf_args = getattr(current_app.extensions['migrate'], 'configure_args', {})

# Set the process_revision_directives if not already set
if conf_args.get("process_revision_directives") is None:
    conf_args["process_revision_directives"] = process_revision_directives


def run_migrations_offline():
    """Runs migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    alembic_context.configure(
        url=url, target_metadata=target_metadata, literal_binds=True
    )

    with alembic_context.begin_transaction():
        alembic_context.run_migrations()


def run_migrations_online():
    """Runs migrations in 'online' mode."""
    start_mappers(current_app)

    connectable = get_engine()
    with connectable.connect() as connection:
        alembic_context.configure(
            connection=connection,
            target_metadata=target_metadata,
            **conf_args
        )

        with alembic_context.begin_transaction():
            alembic_context.run_migrations()


if alembic_context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
