"""add_dictionary_tables_and_remove_logs

Revision ID: fa9b2e01010f
Revises: 048952c16a98
Create Date: 2026-07-14 12:01:16.511347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa9b2e01010f'
down_revision = '048952c16a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dictionary_sources', schema=None) as batch_op:
        batch_op.create_index('idx_sources_type_lookup', ['source_type'], unique=False)

    op.create_table('dictionary_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('viet_word', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('english_translation', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viet_word')
    )
    with op.batch_alter_table('dictionary_words', schema=None) as batch_op:
        batch_op.create_index('idx_viet_word_prefix', ['viet_word'], unique=False)

    op.create_table('han_viet_roots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('root', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('chinese_character', sa.String(length=10, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('root_meaning', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dictionary_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.Text(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('english_translation', sa.Text(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['dictionary_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['dictionary_words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dictionary_examples', schema=None) as batch_op:
        batch_op.create_index('idx_word_examples_lookup', ['word_id', 'created_at'], unique=False)

    op.create_table('word_han_viet_association',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['root_id'], ['han_viet_roots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['dictionary_words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id', 'root_id')
    )
    op.drop_table('logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('word_han_viet_association')
    with op.batch_alter_table('dictionary_examples', schema=None) as batch_op:
        batch_op.drop_index('idx_word_examples_lookup')

    op.drop_table('dictionary_examples')
    op.drop_table('users')
    op.drop_table('han_viet_roots')
    with op.batch_alter_table('dictionary_words', schema=None) as batch_op:
        batch_op.drop_index('idx_viet_word_prefix')

    op.drop_table('dictionary_words')
    with op.batch_alter_table('dictionary_sources', schema=None) as batch_op:
        batch_op.drop_index('idx_sources_type_lookup')

    op.drop_table('dictionary_sources')
    # ### end Alembic commands ###
